### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by avital** [brain-research/realistic-ssl-evaluation#1]
Subscribe to this issue to get notified when the code is released and pushed to this repository.

**Comment by srp33** [comment]
Even if you could just release a preliminary version of the code for applying SSL methods, that would be helpful...

**Comment by yanshuaicao** [comment]
Is the code going to be a set of standalone tools/library or a framework? How easy would it be to try out models in pytorch with this evaluation codebase?

**Comment by avital** [comment]
The code is in TensorFlow, and uses [tf.data.Dataset](https://www.tensorflow.org/api_docs/python/tf/data/Dataset]) for the data loading pipeline for all of the experiments.

Unfortunately, the code was not designed with other machine learning frameworks in mind.

**Comment by AhmedAyad89** [comment]
Do you have an ETA on the release?

**Comment by avital** [comment]
I want to say 2 weeks.

**Comment by wenli-vision** [comment]
Look forward to the release...

**Comment by Anierin** [comment]
Do you have an new ETA on the release?

**Comment by avital** [comment]
Sadly, there have been some internal challenges with the open source release. I am currently unable to estimate the time to release.

**Comment by srp33** [comment]
In my opinion, you should update your preprint accordingly. It should not indicate that the code is available when it is not. Perhaps it even makes sense to withdraw the preprint until this is worked out.

**Comment by avital** [comment]
I will update the preprint to say that the open source release is pending, rather than that is is available.

To clarify, the delay is not due to any doubts we have on the validity of our results -- it is entirely due to internal procedural issues.

**Comment by Anierin** [comment]
Thank you for answering

**Comment by renan-r-santos** [comment]
Hi @avital 
Was the idea of making an open source release dropped out?

**Comment by constant5** [comment]
I'm looking forward to the release.

**Comment by toushi68** [comment]
Is it time now to release?

**Comment by avital** [comment]
We are very close now.

**Comment by liangzimei** [comment]
looking forward

**Comment by pollenjp** [comment]
looking forward

**Comment by yoosan** [comment]
looking forward

**Comment by bl0** [comment]
looking forward

**Comment by DoctorTeeth** [comment]
🦅

**Comment by DoctorTeeth** [comment]
This is released now.
