### ISSUE TITLE
Randomness in build_tfrecords.py + label maps

### ISSUE THREAD

**Issue by michalzajac-ml** [brain-research/realistic-ssl-evaluation#17]
Hi @avital , first of all thanks for releasing the code, I find it very elegant, and tmuxp sessions for every experiment are really cool!

There is information in the README that in order to have exactly the same labeled/unlabeled divisions as in the paper, one has to use label maps from the repo. But the issue is, in order to run the experiments one has to first build tfrecords, which uses random shuffle. This means we HAVE TO create new label maps for these newly created tfrecords.
Am I missing something, or there is really an issue here? How can we generate exactly the same tfrecords as in your experiments?

**Comment by xgastaldi** [comment]
Same question here

**Comment by craffel** [comment]
Thanks for pointing this out. We will investigate whether it's possible to get the desired behavior from appropriate settings of random seed.
