### ISSUE TITLE
Why use WRN-28-2?

### ISSUE THREAD

**Issue by bl0** [brain-research/realistic-ssl-evaluation#2]
Hi, I wonder why you use WRN-28-2 instead of standard resent and widely used 10 layer ConvNet in Π-Model, Mean Teacher, and VAT.
Thanks!

**Comment by avital** [comment]
We intentionally chose a standard architecture that's /not/ what any one paper used. This is with the goal of evaluating the SSL techniques themselves, rather than how they happen to perform on specific architectures that may have been chosen because they are SOTA on those techniques.
