### ISSUE TITLE
How is the error rate and uncertainty calculated?

### ISSUE THREAD

**Issue by varunnair18** [brain-research/realistic-ssl-evaluation#29]
Hello,

From reading the paper, it seems that the error rates are calculated from the test error chosen at the point of lowest validation error, is that correct? 

Also, do you perform experiments with multiple random seeds, or is uncertainty calculated using several different validation sets? How exactly was that uncertainty calculated? Forgive me if I missed it as a detail in your paper.

Thank you!

**Comment by craffel** [comment]
Hi,

> From reading the paper, it seems that the error rates are calculated from the test error chosen at the point of lowest validation error, is that correct?

Yes.

> do you perform experiments with multiple random seeds

Yes.

> is uncertainty calculated using several different validation sets?

The same validation/text set is used in each experiment.
