### ISSUE TITLE
Script for downloading and preprocessing CIFAR and svhn dataset

### ISSUE THREAD

**Issue by AngranLi** [brain-research/realistic-ssl-evaluation#32]
Hi thanks a lot for your work! In the readme you said you have the script for downloading and preprocessing CIFAR and svhn dataset, but I didn't find it in the repository. Could you please describe how you preprocess the data for training? 

Thank you!

**Comment by craffel** [comment]
Yes, see https://github.com/brain-research/realistic-ssl-evaluation/blob/master/build_tfrecords.py
