### ISSUE TITLE
where is data augmentation performed?

### ISSUE THREAD

**Issue by hzhz2020** [brain-research/realistic-ssl-evaluation#34]
Hi, thanks for your inspiring work "Realistic Evaluation of Deep Semi-Supervised Learning Algorithms". In the paper Appendix B you mentioned data augmentation is performed. When I look at the code in the repo, I couldn't find where they are performed. I'm sorry if I overlook anything, but I would really appreciate if you can point it out.

**Comment by craffel** [comment]
It's performed here: https://github.com/brain-research/realistic-ssl-evaluation/blob/3ee69a04994364f7d120a4b919da863d2ab3e66e/lib/networks.py#L140
