### ISSUE TITLE
consistency_model=mean_teacher, when you do fully supervised learning

### ISSUE THREAD

**Issue by TheRevanchist** [brain-research/realistic-ssl-evaluation#8]
Hi,

I saw that you're using consistency model=mean_teacher even in cases where you are doing fully supervised learning. In fact, if we look at the yml files:

 table-1-cifar10-4000-fullysup.yml and table-1-cifar10-4000-mean-teacher.yml

we see that the only difference between them is on:

--hparam_string="max_cons_multiplier=0" for fully_supervised and
--hparam_string="" for the mean teacher.

Am I right on this assumption, and can you please explain me how does the model needs where to do fully_supervised vs mean_teacher?

**Comment by craffel** [comment]
max_cons_multiplier=0 multiplies the consistency cost (i.e., the cost on unlabeled data) by 0. So, it doesn't matter which consistency model is being used; the cost is 0 and unlabeled data is ignored.
